### ISSUE TITLE
eeprom schreiben per cc1101_xxx fehlerhaft

### ISSUE THREAD

**Issue by habeIchVergessen** [RFD-FHEM/SIGNALESP#10]
der übermittelte Index muss um 1 erhöht werden, damit die Änderungen korrekt geschrieben werden (reg+1). s. 3794e586a29ad796ef42a1f8a2519a6418671065

**Comment by sidey79** [comment]
soeben mit einem cherrypick behoben
47635a43ebb4c96286ece4c16ce79dea8ab33a21
