### ISSUE TITLE
kein Empfang

### ISSUE THREAD

**Issue by Heiner1967** [RFD-FHEM/SIGNALESP#19]
Hi, ich habe schon einen Signalduino basierend auf einem Nano in Betrieb und mochte jetzt einen weiteren basierend auf einem nodemcu V3 also 8266 bauen. Ich habe sowohl das letzte Release als auch die letzte Version als fertiges HEX genommen und geflasht. ich sehe die Signalesp einwandfrei in fhem und ein ping funktioniert. Ich empfange aber keinerlei Signale - Nur mit dem alten nano basierten Signalduino.

Also muss etwas mit dem Empfanger nicht stimmen. Wiki und auch der Code sagen D2 ist der richtige Pin, jedoch steht im Code auch noch was von Pin 5 wo kommt das her, stimmt das? Ein Internetrecherche bringt mir noch den GPIO Port aber nicht diese Pin bezeichung.

Was sonst kann ich noch tun um den Fehler zu finden. Habe bereits 2 unterschiedliche Emfaengermodule benutzt

**Comment by HomeAutoUser** [comment]
Hallo @Heiner1967,

mache bitte mal ein Foto oder Fotos von deiner Handware und deiner Verkabelung.
Welchen Empfänger möchtest du nutzen?

**Comment by Heiner1967** [comment]
![Uploading WIN_20200418_14_28_06_Pro.jpg…]()
![Uploading WIN_20200418_14_27_26_Pro.jpg…]()



Habe diesen Sender und Emfaenger besorgt: https://www.ebay.de/itm/RF-Modul-433-MHz-Superheterodyne-Empfanger-und-Sender-Kit-Fur-ArduiDJ-ZF/153691394278?hash=item23c8b890e6:g:wLsAAOSwNRJcejtJ

**Comment by Heiner1967** [comment]
![15872155322365062895396169131885](https://user-images.githubusercontent.com/55279314/79638677-0acd0d80-8187-11ea-9260-9fae8f150615.jpg)

**Comment by Heiner1967** [comment]
![15872155804853267300121679119177](https://user-images.githubusercontent.com/55279314/79638690-220bfb00-8187-11ea-9fbd-f87926743726.jpg)

**Comment by Heiner1967** [comment]
Sorry aber Fotos klappen nur über das Handy

**Comment by elektron-bbs** [comment]
Eigentlich müsste GPIO4 und GPIO5 passen:

```
	#ifdef ESP8266
		#define PIN_RECEIVE            5// D1
		#define PIN_LED                16
		#define PIN_SEND               4// D2  // gdo0Pin TX out
```

Allerdings gibt es wohl auch ESP8266-12, wo diese beiden Anschlüsse vertauscht sind, siehe z.B.: https://github.com/esp8266/Arduino/issues/437

**Comment by sidey79** [comment]
https://www.theengineeringprojects.com/2018/10/introduction-to-nodemcu-v3.html

Hier ist das Pinout hinterlegt, das sieht aber nicht anders aus. D1 = 5.

Hast Du genug Strom für den Empfänger?

**Comment by sidey79** [comment]
Wenn ich mit die beiden Fotos so ansehen. Kann es sein, dass Du dem Empfänger und Sender vertauscht hast?
Vielleicht beginnst Du erst einmal nur mit dem Empfänger. Ich nehme an, das kleinere Gerät ist die Sendeeinheit und die hängt am schwarzen Kabel an D1.

Wenn das stimmt, dann hast Du VIN und GND auf den Empfänger gelegt. Gut möglich, dass der dann auch 5v auf dem Data Pin anliegen hat, was einen ESP grillt, da der nur 3,3v auf den GPIOs verträgt.

**Comment by Heiner1967** [comment]
Hi, ahb jetzt noch mal anderen Code drauf geflasht um den Port zu checken, der geht einwandfrei, hab also nix kaputt gemacht.
Und der 433 Emfaenger an sich kann 3-5 V.

**Comment by HomeAutoUser** [comment]
Hallo @Heiner1967 
wenn du von flashen und dann von anderem Code schreibst, welchen hast du denn als Grundlage genommen ;) ?

Liebe Grüße

**Comment by Heiner1967** [comment]
Hi, ich habe mit ESP Home einen einfachen Code geschrieben:

`esphome:
  name: test
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "xx"
  password: "xx"

ota:

web_server:
  port: 80
  
binary_sensor:
  - platform: gpio
    pin: 
      number: D0
      mode: INPUT_PULLUP
    name: "D0"
    filters:
      - delayed_off: 10ms

  - platform: gpio
    pin: 
      number: D1
      mode: INPUT_PULLUP
    name: "D1"
    filters:
      - delayed_off: 10ms
 
  - platform: gpio
    pin: 
      number: D2
      mode: INPUT_PULLUP
    name: "D2"
    filters;'

Und dann webseite aufmachen, mit einer Drahtbruecke 3V an den Pin legen und schon zeigts die Webseite an. Pins gehen also.

**Comment by elektron-bbs** [comment]
Nochmal die Frage: Welche Firmware hast du geflasht?
Diese sollte die richtige sein:

`https://github.com/RFD-FHEM/SIGNALDuino/releases/download/3.4.0-dev%2B20200216/SIGNALDuino_ESP82663.4.0-dev+20200216.bin.hex`

Hast du ein Messgerät?
Wenn ja, dann miss bitte mal die Ausgangsspannung an D0. Dort sollte die Spannung zumindest "wackeln". Wenn dauerhaft auf 0 Volt oder Betriebsspannung ist sicher der Empfänger defekt. Noch besser wäre natürlich ein Logik-Analyzer oder Oszi.

Es könnte auch noch sein, das der Empfänger einen Ausgang mit Open Kollektor hat. Dann brauchst du einen Pullup-Widerstand gegen VCC.
@sidey79 Oder hast du den internen Pullup vom ESP8266 sowieso eingeschaltet?

**Comment by Heiner1967** [comment]
Hi, ja genau die hab ich drauf. Und wie gesagt mein fhem sagt auch das Ding ist da aber halt mit LASTDMSG nothing
Ich hab so einen slebstbau oszi und der zeigt auch schoen 3v rechtecksignale vom Emfaenger.

Aber warum D0, ich hab den auf D2. checking, shit sollte D1 sein

Last DMESG immer noch leer, doch moment, unknown messages da ist was. Hurra es geht.

Was war das wohl, vermutlich hat das neue flashen geholfen, ich habs nur wegen dem Pindreher nicht gemerkt.

Vielen Dank fuer die Unterstuetzung
