### ISSUE TITLE
Aktueller Stand lässt sich nicht compilieren

### ISSUE THREAD

**Issue by prodigy7** [RFD-FHEM/SIGNALESP#3]
Ich habe den aktuellen Stand aus master ausgecheckt via Git und versucht, mit aktueller VisualStudio 2017 Community Edition und Visual Micro zu compilieren. Kommt hierbei zu folgendem Fehler, wenn ich versuche für NodeMCU zu compilieren:

Visual Micro free version. CTRL+click for secure purchase http://www.visualmicro.com/page/shop.aspx
 
Compiling 'SIGNALESP' for 'NodeMCU 1.0 (ESP-12E Module)'
 
signalDecoder.cpp:34: In file included from
signalDecoder.cpp: In member function void SignalDetectorClass::printMsgStr(const String*, const String*, const String*)
 
output.h: 13:21: error: 'Client' was not declared in this scope
   #define MSG_PRINTER Client \\ Not Implemented at this time
output.h:24: note  in expansion of macro MSG_PRINTER
   #define MSG_PRINT(...) { MSG_PRINTER.print(__VA_ARGS__); }
signalDecoder.cpp:826: note  in expansion of macro MSG_PRINT
   MSG_PRINT(*first)
 
output.h: 13:21: error: 'Client' was not declared in this scope
   #define MSG_PRINTER Client \\ Not Implemented at this time
output.h:24: note  in expansion of macro MSG_PRINTER
   #define MSG_PRINT(...) { MSG_PRINTER.print(__VA_ARGS__); }
signalDecoder.cpp:827: note  in expansion of macro MSG_PRINT
   MSG_PRINT(*second)
 
output.h: 13:21: error: 'Client' was not declared in this scope
   #define MSG_PRINTER Client \\ Not Implemented at this time
output.h:24: note  in expansion of macro MSG_PRINTER
   #define MSG_PRINT(...) { MSG_PRINTER.print(__VA_ARGS__); }
signalDecoder.cpp:828: note  in expansion of macro MSG_PRINT
   MSG_PRINT(*third)
signalDecoder.cpp: In member function int8_t SignalDetectorClass::printMsgRaw(uint8_t, uint8_t, const String*, const String*)
 
output.h: 13:21: error: 'Client' was not declared in this scope
   #define MSG_PRINTER Client \\ Not Implemented at this time
output.h:24: note  in expansion of macro MSG_PRINTER
   #define MSG_PRINT(...) { MSG_PRINTER.print(__VA_ARGS__); }
signalDecoder.cpp:834: note  in expansion of macro MSG_PRINT
   MSG_PRINT(*preamble)
 
output.h: 13:21: error: 'Client' was not declared in this scope
   #define MSG_PRINTER Client \\ Not Implemented at this time
output.h:24: note  in expansion of macro MSG_PRINTER
   #define MSG_PRINT(...) { MSG_PRINTER.print(__VA_ARGS__); }
signalDecoder.cpp:842: note  in expansion of macro MSG_PRINT
   MSG_PRINT(message[m_start])
 
output.h: 13:21: error: 'Client' was not declared in this scope
   #define MSG_PRINTER Client \\ Not Implemented at this time
output.h:24: note  in expansion of macro MSG_PRINTER
   #define MSG_PRINT(...) { MSG_PRINTER.print(__VA_ARGS__); }
signalDecoder.cpp:848: note  in expansion of macro MSG_PRINT
   MSG_PRINT(*postamble)
Error compiling libraries
Build failed for project 'SIGNALESP'

**Comment by sidey79** [comment]
Kannst Du es noch mal aktualisieren und es probieren?
Ich habe etwas angepasst:
85c9e590e522b849356fd160c52076cdea7e199b

**Comment by prodigy7** [comment]
Es wird besser (meckert nicht mehr fehlende Dateien an):

Visual Micro free version. CTRL+click for secure purchase http://www.visualmicro.com/page/shop.aspx

Compiling 'SIGNALESP' for 'NodeMCU 1.0 (ESP-12E Module)'
 
signalDecoder.cpp:34: In file included from
Error compiling libraries
signalDecoder.cpp: In member function void SignalDetectorClass::printMsgStr(const String*, const String*, const String*)
Build failed for project 'SIGNALESP'
 
output.h: 13:21: error: 'Client' was not declared in this scope
   #define MSG_PRINTER Client \\ Not Implemented at this time
output.h:24: note  in expansion of macro MSG_PRINTER
   #define MSG_PRINT(...) { MSG_PRINTER.print(__VA_ARGS__); }
signalDecoder.cpp:826: note  in expansion of macro MSG_PRINT
   MSG_PRINT(*first)
 
output.h: 13:21: error: 'Client' was not declared in this scope
   #define MSG_PRINTER Client \\ Not Implemented at this time
output.h:24: note  in expansion of macro MSG_PRINTER
   #define MSG_PRINT(...) { MSG_PRINTER.print(__VA_ARGS__); }
signalDecoder.cpp:827: note  in expansion of macro MSG_PRINT
   MSG_PRINT(*second)
 
output.h: 13:21: error: 'Client' was not declared in this scope
   #define MSG_PRINTER Client \\ Not Implemented at this time
output.h:24: note  in expansion of macro MSG_PRINTER
   #define MSG_PRINT(...) { MSG_PRINTER.print(__VA_ARGS__); }
signalDecoder.cpp:828: note  in expansion of macro MSG_PRINT
   MSG_PRINT(*third)
signalDecoder.cpp: In member function int8_t SignalDetectorClass::printMsgRaw(uint8_t, uint8_t, const String*, const String*)
 
output.h: 13:21: error: 'Client' was not declared in this scope
   #define MSG_PRINTER Client \\ Not Implemented at this time
output.h:24: note  in expansion of macro MSG_PRINTER
   #define MSG_PRINT(...) { MSG_PRINTER.print(__VA_ARGS__); }
signalDecoder.cpp:834: note  in expansion of macro MSG_PRINT
   MSG_PRINT(*preamble)
 
output.h: 13:21: error: 'Client' was not declared in this scope
   #define MSG_PRINTER Client \\ Not Implemented at this time
output.h:24: note  in expansion of macro MSG_PRINTER
   #define MSG_PRINT(...) { MSG_PRINTER.print(__VA_ARGS__); }
signalDecoder.cpp:842: note  in expansion of macro MSG_PRINT
   MSG_PRINT(message[m_start])
 
output.h: 13:21: error: 'Client' was not declared in this scope
   #define MSG_PRINTER Client \\ Not Implemented at this time
output.h:24: note  in expansion of macro MSG_PRINTER
   #define MSG_PRINT(...) { MSG_PRINTER.print(__VA_ARGS__); }
signalDecoder.cpp:848: note  in expansion of macro MSG_PRINT
   MSG_PRINT(*postamble)

**Comment by sidey79** [comment]
Ich habs jetzt ausprobiert, so geht es bei mir :)

**Comment by prodigy7** [comment]
Danke, jetzt hat es geklappt! :-) 

Visual Micro free version. CTRL+click for secure purchase http://www.visualmicro.com/page/shop.aspx

Compiling 'SIGNALESP' for 'NodeMCU 1.0 (ESP-12E Module)'
Program size: 320.270 bytes (used 31% of a 1.044.464 byte maximum) (39,28 secs)
Minimum Memory Usage: 37700 bytes (46% of a 81920 byte maximum)
