### ISSUE TITLE
cc1101 Branch compiliert nicht

### ISSUE THREAD

**Issue by prodigy7** [RFD-FHEM/SIGNALESP#5]
Quellcode lässt sich aktuell nicht compilieren.

Visual Micro free version. CTRL+click for secure purchase http://www.visualmicro.com/page/shop.aspx

Compiling 'SIGNALESP' for 'NodeMCU 1.0 (ESP-12E Module)'
 
signalDecoder.cpp:31: In file included from
 
signalDecoder.h: 43:26: fatal error: FastDelegate.h: No such file or directory
   #include "FastDelegate.h"
   compilation terminated
Error compiling libraries
Build failed for project 'SIGNALESP'

**Comment by sidey79** [comment]
Ich hatte vergessen, die Projektdatei auch zu committen in der vermerkt ist, dass FastDelegate.h vorhanden ist.

55f045d

**Comment by prodigy7** [comment]
Danke, läuft jetzt durch

Visual Micro free version. CTRL+click for secure purchase http://www.visualmicro.com/page/shop.aspx

Compiling 'SIGNALESP' for 'NodeMCU 1.0 (ESP-12E Module)'
Program size: 324.374 bytes (used 31% of a 1.044.464 byte maximum) (6,41 secs)
Minimum Memory Usage: 37688 bytes (46% of a 81920 byte maximum)
